// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv3yjwm2K3LenkX1ZNSolXUCRuWUqQbkE',
    appId: '1:119234458761:web:d3d951b4e55075b4700258',
    messagingSenderId: '119234458761',
    projectId: 'shop-smart-b200a',
    authDomain: 'shop-smart-b200a.firebaseapp.com',
    storageBucket: 'shop-smart-b200a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPcih4zvRb2ntHdB68ZJbJt_3PDcgt_hQ',
    appId: '1:119234458761:android:8ef42588daee5b1b700258',
    messagingSenderId: '119234458761',
    projectId: 'shop-smart-b200a',
    storageBucket: 'shop-smart-b200a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGlvUH3-61_TjMYE8i-afkRknGS_-xFTU',
    appId: '1:119234458761:ios:7df33a81a9598e08700258',
    messagingSenderId: '119234458761',
    projectId: 'shop-smart-b200a',
    storageBucket: 'shop-smart-b200a.appspot.com',
    iosClientId: '119234458761-81jgi01508cg0b5brtchls9ngs0sgiho.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGlvUH3-61_TjMYE8i-afkRknGS_-xFTU',
    appId: '1:119234458761:ios:8a4840a53be3953b700258',
    messagingSenderId: '119234458761',
    projectId: 'shop-smart-b200a',
    storageBucket: 'shop-smart-b200a.appspot.com',
    iosClientId: '119234458761-dnkusoh5gbjk8qn2erfobh1dnqsfdsb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartShop.RunnerTests',
  );
}
